from django.core.exceptions import ImproperlyConfigured

AUTH_TOKEN_KEY = "user_token"

